### ISSUE TITLE
memory leak in router

### ISSUE THREAD

**Issue by reinholdk** [aurelia/router#207]
I have a scenario with router and child router which leads to a memory leak. View models instantiated by the child router are still being referenced when navigating away.
I have built the scenario in the following Plunker [http://embed.plnkr.co/n5W1JA/preview].
The child router is part of the view model called "second". It allows to toggle between two view models, "child1" and "child2".
The leak can be observed by navigating to the "second" view and toggling between "child1" and "child2".
Each navigation to "child1" creates an new instance of the view model. A heap snapshot reveals that the instances of the view model do not get cleaned-up, even when navigating to the other top-level view "first".
For easy lookup in the heap snapshot, child1 initializes a property with an instance of a class called "LeakTag".  So just filter the snapshot for that class and you'll see the growing number of instances.

**Comment by jdanyow** [comment]
@reinholdk this issue may have been fixed by some fixes to the binding system that have not been released yet.  I'd like to test your specific test case but I'm not able to access the plunker you put together.  Would you be able to re-post the plunker or create a new one using http://bit.ly/aurelia-plunker ?

**Comment by reinholdk** [comment]
Strange, I can still see the plunk even when not logged-in to Plunker, it is marked as public plunk.
This is the editor URL exposed when pressing the share as e-mail button: http://plnkr.co/edit/n5W1JA?p=info maybe it works better.

**Comment by jdanyow** [comment]
@reinholdk thanks- I'm able to access it using both links now.  Turns out plunker was down for a little while yesterday.

I'll do some testing with the new bits and report back.

**Comment by jdanyow** [comment]
Debugged this with the latest versions of binding, templating, etc.  There are still some leaks.  Still working on plugging them.
https://github.com/aurelia/templating-binding/commit/feedc533ca132b392b887094cc7df6193c6d2033

**Comment by EisenbergEffect** [comment]
@jdanyow Was this fixed? Can we close now?

**Comment by jdanyow** [comment]
I believe there still is a leak in the router, somewhere in the "instructions" / "previous instructions".  I'll need to re-test.

**Comment by bryanrsmith** [comment]
@jdanyow Let me know if you want me to check this out.

**Comment by EisenbergEffect** [comment]
Perhaps once the navigation is complete we need to null out certain parts of the previous instruction? We need to keep part of it around in order to enable correct navigation logic, but we might need to null out everything else in order to clean up the model references. Just thinking out loud here...
